CUDA_VISIBLE_DEVICES=7 OMP_NUM_THREADS=12 NUM_THREADS=12 python scripts/test_toolpose_segmentation_on_videos_v3.py --videos_dir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/clipped_videos/P14/ --video_fname_id _EndoRight.mp4 --expt_savedir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0 --expt_name fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/temp2/ --model_type FCN --num_videos -1 --input_width 640 --input_height 480 --score_detection_threshold 0.5 --area_threshold 11 --dist_threshold 110 --load_wts_model /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0/fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/ckpts/model_005.pth --orig_width 1920 --orig_height 1080 --crop_width 1440 --crop_height 1080

CUDA_VISIBLE_DEVICES=7 OMP_NUM_THREADS=12 NUM_THREADS=12 python scripts/test_toolpose_segmentation_on_videos_v3.py --videos_dir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/clipped_videos/P15/ --video_fname_id _EndoRight.mp4 --expt_savedir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0 --expt_name fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/temp2/ --model_type FCN --num_videos -1 --input_width 640 --input_height 480 --score_detection_threshold 0.5 --area_threshold 11 --dist_threshold 110 --load_wts_model /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0/fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/ckpts/model_005.pth --orig_width 1920 --orig_height 1080 --crop_width 1440 --crop_height 1080

CUDA_VISIBLE_DEVICES=7 OMP_NUM_THREADS=12 NUM_THREADS=12 python scripts/test_toolpose_segmentation_on_videos_v3.py --videos_dir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/clipped_videos/P16/ --video_fname_id _EndoRight.mp4 --expt_savedir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0 --expt_name fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/temp2/ --model_type FCN --num_videos -1 --input_width 640 --input_height 480 --score_detection_threshold 0.5 --area_threshold 11 --dist_threshold 110 --load_wts_model /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0/fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/ckpts/model_005.pth --orig_width 1920 --orig_height 1080 --crop_width 1440 --crop_height 1080

CUDA_VISIBLE_DEVICES=7 OMP_NUM_THREADS=12 NUM_THREADS=12 python scripts/test_toolpose_segmentation_on_videos_v3.py --videos_dir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/clipped_videos/P17/ --video_fname_id _EndoRight.mp4 --expt_savedir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0 --expt_name fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/temp2/ --model_type FCN --num_videos -1 --input_width 640 --input_height 480 --score_detection_threshold 0.5 --area_threshold 11 --dist_threshold 110 --load_wts_model /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0/fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/ckpts/model_005.pth --orig_width 1920 --orig_height 1080 --crop_width 1440 --crop_height 1080

CUDA_VISIBLE_DEVICES=7 OMP_NUM_THREADS=12 NUM_THREADS=12 python scripts/test_toolpose_segmentation_on_videos_v3.py --videos_dir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/clipped_videos/P19/ --video_fname_id _EndoRight.mp4 --expt_savedir /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0 --expt_name fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/temp2/ --model_type FCN --num_videos -1 --input_width 640 --input_height 480 --score_detection_threshold 0.5 --area_threshold 11 --dist_threshold 110 --load_wts_model /rhf/bg40/Rice-Methodist-Surgical-Skills-Assessement-Data-2025/mfcnet_runs0/fcn_pretrainedonJIGSAWS_lr3e-5_stepDecay_epochs05_full/ckpts/model_005.pth --orig_width 1920 --orig_height 1080 --crop_width 1440 --crop_height 1080

